### ISSUE TITLE
How to restore bootloader partition after corrupting it?

### ISSUE THREAD

**Issue by Grimler91** [frederic/exynos-usbdl#1]
Hi,

Thanks for the interesting [writeup](https://fredericb.info/2020/06/exynos-usbdl-unsigned-code-loader-for-exynos-bootrom.html), and for releasing the code.

I was wondering if you could clarify how the bootloader partition restoration could be done, basically I do not dare try out the tool before I am sure I can un-brick the device afterwards.. :)

Do I understand it correctly that we will not be able to access download mode once the bootloader partition is corrupted? 
If yes, then that mean that restoring the partition can only be done through usbdl (somehow), or maybe by using samsung's kies software?

**Comment by VDavid003** [comment]
Since we never got an answer I bought a test phone to mess with stuff like this. I tried it on an Exynos 7885 phone. After corrupting the bootloader and then sending the original one (split up correctly, that took a bit to get right) it booted straight to download mode. From there you can flash a working bootloader.

**Comment by Grimler91** [comment]
@VDavid003 great :+1: could you share the offsets used to split the sboot for that device? I have access to a 7420, a 7880 and a 7904 device, and I bet at least the latter two has similar offsets

**Comment by VDavid003** [comment]
> @VDavid003 great 👍 could you share the offsets used to split the sboot for that device? I have access to a 7420, a 7880 and a 7904 device, and I bet at least the latter two has similar offsets

Since exynos7904 is just a downclocked 7885, that will definitely work. This is the split script I used for 7885. (sent as .txt instead of sh because of github not supporting .sh) You only need to send part 1-5 to the phone for it to boot into download mode.
[split_7885_sboot.sh.txt](https://github.com/frederic/exynos-usbdl/files/8580041/split_7885_sboot.sh.txt)

I'd guess 7880 would have a layout more similiar to 8890 where there are only 4 parts. Never checked though.

**Comment by Grimler91** [comment]
Thanks, closing this since booting through usb upload is definitely the way to go!
